name: "OpenAPI Diff"

description: "A GitHub Action to identify differences between Swagger or OpenApi specifications."

branding:
  icon: check-square
  color: gray-dark

inputs:
  base-spec:
    description: "Path to the BASE Swagger or OpenApi specification file."
    required: true
  head-spec:
    description: "Path to the HEAD Swagger or OpenApi specification file."
    required: true

outputs:
  diff-output:
    description: "Ouput of the diff."

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.base-spec }}
    - ${{ inputs.head-spec }}
